---
- name: Stop sssd
  service:
    name: sssd
    state: stopped

- name: Start sssd
  service:
    name: sssd
    state: started

- name: Restart sssd
  service:
    name: sssd
    state: restarted
